var slime_character = new Character("Slime", new Animation("sli",
							   Sprite.slime, 0, 0, 1, 1),
				    new Action("tackle", Action_Type.Enemy_Single,
					       function(target){target.take_damage(3);},
					       new Animation("slime1",
							     Sprite.slime, 0, 0,
							     2, 2),
					       new Animation("tackle",
							     Sprite.action_tackle)),
				    new Action("heal", Action_Type.Ally_Single,
					       function(target){target.take_damage(-1);},
					       new Animation("slime2",
							     Sprite.slime, 0, 0,
							     2, 2),
					       new Animation("Heal",
							     Sprite.action_heal)));
var fight_character =
    new Character("Fighter", new Animation("fig", Sprite.fighter),
		  new Action("Punch", Action_Type.Enemy_Single,
			     function(target){target.take_damage(2);},
			     new Animation("fig", Sprite.fighter,
					   0, 0, 2, 1.5),
			     new Animation("punch",
					   Sprite.action_punch)),
		  new Action("Super Punch", Action_Type.Enemy_Single,
			     function(target){target.take_damage(3);},
			     new Animation("fig", Sprite.fighter,
					   1, 0, 2, 1.5),
			     new Animation("super_punch",
					   Sprite.action_super_punch)));
combat.ally_party.add_member(slime_character);
