var slime_character = new Character("Slime", new Animation("sli",
							   Sprite.slime, 0, 0, 1, 1),
				    new Action("tackle", Action_Type.Enemy_Single,
					       function(target){target.health-=3;},
					       new Animation("slime1",
							     Sprite.slime, 0, 0,
							     2, 2),
					       new Animation("tackle",
							     Sprite.action_tackle)),
				    new Action("heal", Action_Type.Ally_Single,
					       function(target){target.health+=1;},
					       new Animation("slime2",
							     Sprite.slime, 0, 0,
							     2, 2),
					       new Animation("Heal",
							     Sprite.action_heal)));
var fight_character =
    new Character("Fight", new Animation("fig", Sprite.green),
		  new Action("tackle", Action_Type.Enemy_Single,
			     function(target){target.health-=2;},
			     null,
			     new Animation("punch",
					   Sprite.action_punch)),
		  new Action("fight it", Action_Type.Enemy_Single,
			     function(target){target.health-=1;},
			     null,
			     new Animation("super_punch",
					   Sprite.action_super_punch)));
combat.ally_party.add_member(slime_character);
//combat.ally_party.add_member(fight_character);
